### PR TITLE
update grunt dependency

### PR DESCRIPTION
**Pull request by jerryorta-dev**

### CODE REVIEW

**Comment by monolithed** [comment]
Grunt is a `peerDependencies` why do you want to replace it with `dependencies`?

**Comment by jerryorta-dev** [comment]
Let me fix that

**Comment by jerryorta-dev** [comment]
PR updated

**Comment by monolithed** [comment]
@shootaroo, could you accept the PR?

**Comment by henrahmagix** [comment]
The current peer dependency covers more versions of grunt without negative affect. This change would remove compatibility with grunt 0.4.x, which I don't think is a good thing.

I have a feeling you are using npm 2 which installs peer dependencies (npm 3 does not) and you want to use grunt 1.x? If so, you can install grunt as a dependency to your project (recommended) at whichever version you want, and jit-grunt will work with it.

`npm install --save-dev grunt@latest`

**Pull request closed without merging**
